title: WordPlate
description: WordPlate is a modern WordPress stack built with Composer. It simplifies the fuzziness around WordPress development.
url: https://wordplate.github.io/
author:
  name: Vincent Klaiber
  picture: https://avatars2.githubusercontent.com/u/11923978
  twitter: vinkla

twitter:
  username: vinkla

logo: https://avatars2.githubusercontent.com/u/11923978

exclude: [Gemfile, Gemfile.lock, LICENSE, README.md]

sass:
  style: compressed
  sass_dir: assets/styles

gems:
  - jekyll-feed
  - jekyll-mentions
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji
